name: publish

on:
  issues:
    types:
      - labeled

jobs:
  get-all-comments:
    if: contains(github.event.issue.labels.*.name, 'publish')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        id: get-comments
        with:
          script: |
            const issue = await github.rest.issues.get({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            console.log(issue);
            const comments = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            console.log(comments);
            
            const text = [issue.data.body].concat(comments.data.map(d=>d.body));
            const docs = {
              title: issue.data.title,
              text: text.join('\n')
            }
            return docs;

      - name: print issue
        run: echo '${{ toJSON(steps.get-comments.outputs.result) }}'
